name: GitHub Pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: npm ci
      - uses: actions/configure-pages@v1
      - name: Build
        run: npm run build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: build
      - uses: actions/deploy-pages@v3
